services:
  postgres:
    image: postgres:16.2-alpine
    container_name: digit2025_postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AXfXj77DSF8e7i2a
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
