services:
  postgres:
    image: postgres:16.2-alpine
    container_name: digit2025_postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AXfXj77DSF8e7i2a
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana

volumes:
  postgres:
